### ISSUE TITLE
illegal expression in **FGSM TARGETED**

### ISSUE THREAD

**Issue by sultanoid** [hammaad2002/ASRAdversarialAttacks#1]
Hi , I have recorded the audio using the following code: 

import sounddevice as sd
from scipy.io.wavfile import write

fs=16000
duration=5
print("recording...............")

record_voice=sd.rec(int(duration * fs),samplerate=fs,channels=2)
sd.wait()       
write("sound.wav",fs,record_voice)

Then I have loaded the the audio using the following code: 

input_audio, sample_rate1 = torchaudio.load('sound.wav')

When I am going to perturb this audio using the following code, I am getting illegal expression. 

temp1 = attack.FGSM_ATTACK(input_audio, target, epsilon = 0.01, targeted = True)

What is the way to record the audio and perturb the audio?

**Comment by hammaad2002** [comment]
Thanks for showing interest in my repo. And unfortunately, the issue you are facing I think it is due to the model configuration meaning that the wav2vec2.0 model is designed for single-channel audios and you have recorded your audio using dual-channel recording. I have created a Google Colab file for the task you want to perform which is to record and perturb the same audio in the notebook hope it will be helpful.
[File](https://colab.research.google.com/drive/1J46ihRxNh-G8hKhqvNiN-a9K0nVR0hhi?usp=sharing)
And still, if you need any help feel free to ask me and would appreciate it if you would star this repository also :)

**Comment by sultanoid** [comment]
Hi, I have starred your repository and working on live audio perturbation. For this, I have taken your code and rewrite my code as follows: 

`import pyaudio
import torchaudio
import torch 
from ASRAdversarialAttacks.AdversarialAttacks import ASRAttacks
from IPython.display import display,Audio
import ffmpeg
from base64 import b64decode
import numpy as np 
from scipy.io.wavfile import read as wav_read

# Set parameters for audio stream
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100
CHUNK_SIZE = 1024

# Initialize PyAudio
p = pyaudio.PyAudio()

# Open audio stream for recording
stream_in = p.open(format=FORMAT,
                   channels=CHANNELS,
                   rate=RATE,
                   input=True,
                   frames_per_buffer=CHUNK_SIZE)

# Open audio stream for playback
stream_out = p.open(format=FORMAT,
                    channels=CHANNELS,
                    rate=RATE,
                    output=True,
                    frames_per_buffer=CHUNK_SIZE)
bundle = torchaudio.pipelines.WAV2VEC2_ASR_BASE_960H
model = bundle.get_model()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

target_transcription = 'WHEN MAN NOTHING KILL IN BIG CAMEL'
true_transcription = 'THE CHILD ALMOST HURT THE SMALL DOG'
attack = ASRAttacks(model, device, bundle.get_labels())
target = list(target_transcription.upper().replace(" ", "|"))

frame = [] 
# Record and play back audio
while True:
    # Read audio data from microphone
    data_in = stream_in.read(CHUNK_SIZE)
    

    # Write audio data to output device
    stream_out.write(data_in)

    binary = b64decode(data_in.split(',')[1].encode())
  
    process = (ffmpeg
        .input('pipe:0')
        .output('pipe:1', format='wav')
        .run_async(pipe_stdin=True, pipe_stdout=True, pipe_stderr=True, quiet=True, overwrite_output=True)
    )
    output, err = process.communicate(input=binary)
    
    # Duplicate mono audio to create two identical channels
    audio = np.repeat(wav_read(io.BytesIO(output))[1][np.newaxis, :], 2, axis=0)
    sr = wav_read(io.BytesIO(output))[0]

    sr = 48000
    audio = audio.astype('int16')
    print(audio.shape)
    torchaudio.save('/content/audioRec.wav', torch.from_numpy(audio), sr)
    # Loading the audio
    input_audio, sample_rate = librosa.load('/content/audioRec.wav', sr = 16000, mono=False)
    print(input_audio.shape)
    torchaudio.save('/content/audioRec.wav', torch.from_numpy(input_audio), 16000)
    rec_audio, sr = torchaudio.load('/content/audioRec.wav')
    print(rec_audio.shape)

    attack = ASRAttacks(model, device, bundle.get_labels())

    #FGSM
    temp1 = attack.FGSM_ATTACK(rec_audio, target, epsilon = 0.01, targeted = True)

    #FGSM PRINT
    print(attack.INFER(torch.from_numpy(temp1)).replace("|"," "))
    print(target_transcription)

    temp1 = attack.FGSM_ATTACK(rec_audio[0].unsqueeze(0), target, epsilon = 0.001, targeted = True)

    #FGSM PRINT
    print(attack.INFER(torch.from_numpy(temp1)).replace("|"," "))
    print(attack.INFER(rec_audio[0].unsqueeze(0)).replace("|"," "))
    print(target_transcription)

    `

But I am getting following error: 

Traceback (most recent call last):
  File "live_fgsm.py", line 54, in <module>
    binary = b64decode(data_in.split(',')[1].encode())
TypeError: a bytes-like object is required, not 'str'

**Comment by sultanoid** [comment]
Hi, I want to perturb the live audio from speaker. For that, I have taken your code and rewrite as follows: 

`
import pyaudio
import torchaudio
import torch 
from ASRAdversarialAttacks.AdversarialAttacks import ASRAttacks
from IPython.display import display,Audio
import ffmpeg
from base64 import b64decode
import numpy as np 
from scipy.io.wavfile import read as wav_read

# Set parameters for audio stream
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100
CHUNK_SIZE = 1024

# Initialize PyAudio
p = pyaudio.PyAudio()

# Open audio stream for recording
stream_in = p.open(format=FORMAT,
                   channels=CHANNELS,
                   rate=RATE,
                   input=True,
                   frames_per_buffer=CHUNK_SIZE)

# Open audio stream for playback
stream_out = p.open(format=FORMAT,
                    channels=CHANNELS,
                    rate=RATE,
                    output=True,
                    frames_per_buffer=CHUNK_SIZE)
bundle = torchaudio.pipelines.WAV2VEC2_ASR_BASE_960H
model = bundle.get_model()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

target_transcription = 'WHEN MAN NOTHING KILL IN BIG CAMEL'
true_transcription = 'THE CHILD ALMOST HURT THE SMALL DOG'
attack = ASRAttacks(model, device, bundle.get_labels())
target = list(target_transcription.upper().replace(" ", "|"))

frame = [] 
# Record and play back audio
while True:
    # Read audio data from microphone
    data_in = stream_in.read(CHUNK_SIZE)
    

    # Write audio data to output device
    stream_out.write(data_in)

    binary = b64decode(data_in.split(',')[1].encode())
  
    process = (ffmpeg
        .input('pipe:0')
        .output('pipe:1', format='wav')
        .run_async(pipe_stdin=True, pipe_stdout=True, pipe_stderr=True, quiet=True, overwrite_output=True)
    )
    output, err = process.communicate(input=binary)
    
    # Duplicate mono audio to create two identical channels
    audio = np.repeat(wav_read(io.BytesIO(output))[1][np.newaxis, :], 2, axis=0)
    sr = wav_read(io.BytesIO(output))[0]

    sr = 48000
    audio = audio.astype('int16')
    print(audio.shape)
    torchaudio.save('/content/audioRec.wav', torch.from_numpy(audio), sr)
    # Loading the audio
    input_audio, sample_rate = librosa.load('/content/audioRec.wav', sr = 16000, mono=False)
    print(input_audio.shape)
    torchaudio.save('/content/audioRec.wav', torch.from_numpy(input_audio), 16000)
    rec_audio, sr = torchaudio.load('/content/audioRec.wav')
    print(rec_audio.shape)

    attack = ASRAttacks(model, device, bundle.get_labels())

    #FGSM
    temp1 = attack.FGSM_ATTACK(rec_audio, target, epsilon = 0.01, targeted = True)

    #FGSM PRINT
    print(attack.INFER(torch.from_numpy(temp1)).replace("|"," "))
    print(target_transcription)

    temp1 = attack.FGSM_ATTACK(rec_audio[0].unsqueeze(0), target, epsilon = 0.001, targeted = True)

    #FGSM PRINT
    print(attack.INFER(torch.from_numpy(temp1)).replace("|"," "))
    print(attack.INFER(rec_audio[0].unsqueeze(0)).replace("|"," "))
    print(target_transcription)

    `

But I am getting error as follows: 

Traceback (most recent call last):
  File "live_fgsm.py", line 54, in <module>
    binary = b64decode(data_in.split(',')[1].encode())
TypeError: a bytes-like object is required, not 'str'

How can I solve this error ? I have starred this repository.

**Comment by sultanoid** [comment]
Hi, I want to perturb the live audio from speaker. More specifically, I want to record the audio and perturb the audio simultaneously.  For that, I have taken your code and rewrite as follows:

https://pastebin.com/xw8ge8QS

But I am getting the following error: 

[Traceback (most recent call last):
  File "live_fgsm.py", line 54, in <module>
    binary = b64decode(data_in.split(',')[1].encode())
TypeError: a bytes-like object is required, not 'str'](url)

It will be great help if you can help me to figure out the error. I have already starred this repository.

**Comment by hammaad2002** [comment]
Sorry for the late reply. I like your idea, but it unfortunately cannot be implemented with the attacks I have implemented in my repository. All the attacks in my repository are static, and the model wav2vec2.0 is also a static model. It is not designed for streaming purposes. For streaming purposes, RNN-T models are used, and attacks are also different for these models. I have not read about attacks on RNN-T models yet, but I can provide you with a link to a research paper that is similar to your [idea](https://arxiv.org/abs/1905.13399)

**Comment by sultanoid** [comment]
Thanks a lot for your information.
